Task 4
SamoylenkVi/cinema-wtw pull request #4
Opened 2023-05-17 10:51 UTC by SamoylenkVi

2023-05-17 15:23 UTC, Pavel-Liteiniy requested changes

2023-05-17 15:23 UTC, Pavel-Liteiniy commented on .eslintrc.js
> +    'react/react-in-jsx-scope': 'off',
[react/react-in-jsx-scope'](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/react-in-jsx-scope.md#when-not-to-use-it)

> If you are not using JSX, or if you are setting React as a global variable.

> If you are using the [new JSX transform from React 17](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#removing-unused-react-imports), you should disable this rule by extending [react/jsx-runtime](https://github.com/jsx-eslint/eslint-plugin-react/blob/8cf47a8ac2242ee00ea36eac4b6ae51956ba4411/index.js#L165-L179) in your eslint config (add "plugin:react/jsx-runtime" to "extends").

2023-05-17 15:23 UTC, Pavel-Liteiniy commented on .eslintrc.js
> +    'react/react-in-jsx-scope': 'off',
So than there is no need to make `import React from 'react'` in all other files - delete everywhere

2023-05-17 15:23 UTC, Pavel-Liteiniy commented on src/components/film-card.jsx
> +  const videoRef = React.createRef();
why not useRef?

2023-05-17 15:23 UTC, Pavel-Liteiniy commented on src/components/film-card.jsx
> +        setVideoError(!isVideoError);
```suggestion
        setVideoError(true);
```

2023-05-17 15:23 UTC, Pavel-Liteiniy commented on src/components/film-card.jsx
> +    <article onMouseEnter={playVideo} onMouseLeave={playVideo} className="small-movie-card catalog__movies-card">
why do you put same cb in opposite handlers?

2023-05-17 15:23 UTC, Pavel-Liteiniy commented on src/components/film-card.jsx
> +        {isVideoError && <img src={previewImage} alt={altText} width="280" height="175" />}
May it happen that there is isVideo and isVideoError in the same time?

2023-05-17 15:23 UTC, Pavel-Liteiniy commented on src/components/film-details-information/film-details-information.jsx
> +                  return <>
use Fragment and add `key` attribute

2023-05-17 15:23 UTC, Pavel-Liteiniy commented on src/components/film-details-information/film-details-information.jsx
> +                return <>
so difficult to read.

Please use this 


```suggestion
                return (
                  <Fragment key={id}>
                    {item}, <br></br>
                  </Fragment>
                );
```

2023-05-17 15:23 UTC, Pavel-Liteiniy commented on src/components/film-details-information/helper.js
helper**s**.js

2023-05-17 15:23 UTC, Pavel-Liteiniy commented on src/components/film-details-navigation/details-navigation.jsx
> +  useEffect(() => {
why?

2023-05-17 15:23 UTC, Pavel-Liteiniy commented on src/components/film-details-navigation/details-navigation.jsx
> +                  {ucFirst(button)}
what does `ucFirst` mean?

2023-05-17 15:23 UTC, Pavel-Liteiniy commented on src/components/film-details-navigation/details-navigation.jsx
> +            <>
You should add key to the root component https://react.dev/learn/rendering-lists

here it's `Fragment`

2023-05-17 15:23 UTC, Pavel-Liteiniy commented on src/components/film-details-navigation/details-navigation.jsx
> +      <FilmDetailsContent film={film} state={currentButton} />
let's rename prop `state` to `currentButton` for example

2023-05-17 15:23 UTC, Pavel-Liteiniy commented on src/components/film-details-navigation/helper.js
> +export const ucFirst = (str) => str[0].toUpperCase() + str.slice(1);
strange name for function - what does it mean?

2023-05-17 15:23 UTC, Pavel-Liteiniy commented on src/components/film-details-navigation/details-navigation.jsx
> +  film: PropTypes.objectOf(),
object of what?

2023-05-17 15:23 UTC, Pavel-Liteiniy commented on src/components/film-details-overview/helper.js
> +const RATING__LEVEL = {
let's move to `constants`

2023-05-17 15:23 UTC, Pavel-Liteiniy commented on src/components/film-details-overview/helper.js
> +const STARRING_MAX = 3;
let's move to `constants`

2023-05-17 15:23 UTC, Pavel-Liteiniy commented on src/components/film-details-overview/helper.js
> +  if (rating < 3) {
3, 5, 8 etc. - magic numbers

2023-05-17 15:23 UTC, Pavel-Liteiniy commented on src/components/film-details-page/helper.js
> +const SIMILAR_FILMS_MAX = 4;
let's move to `constants`

2023-05-17 15:23 UTC, Pavel-Liteiniy commented on src/components/film-details-review/filmDetailsReview.jsx
> +    <>
why do you use fragment here?

2023-05-17 15:23 UTC, Pavel-Liteiniy commented on src/components/film-details-review/filmDetailsReview.jsx
> +  comments: PropTypes.objectOf(),
object of what?

2023-05-18 07:52 UTC, SamoylenkVi commented on src/components/film-card.jsx
> +  const videoRef = React.createRef();
fixed

2023-05-18 07:56 UTC, SamoylenkVi commented on src/components/film-details-overview/helper.js
> +const STARRING_MAX = 3;
fixed

2023-05-18 08:01 UTC, SamoylenkVi commented on src/components/film-details-overview/helper.js
> +  if (rating < 3) {
fixed

2023-05-18 08:02 UTC, SamoylenkVi commented on src/components/film-details-page/helper.js
> +const SIMILAR_FILMS_MAX = 4;
fixed

2023-05-18 08:03 UTC, SamoylenkVi commented on src/components/film-details-review/filmDetailsReview.jsx
> +    <>
fixed

2023-05-19 06:01 UTC, SamoylenkVi commented on .eslintrc.js
> +    'react/react-in-jsx-scope': 'off',
fixed

2023-05-19 06:02 UTC, SamoylenkVi commented on src/components/film-card.jsx
> +        setVideoError(!isVideoError);
fixed

2023-05-19 06:02 UTC, SamoylenkVi commented on src/components/film-card.jsx
> +    <article onMouseEnter={playVideo} onMouseLeave={playVideo} className="small-movie-card catalog__movies-card">
fixed

2023-05-19 06:02 UTC, SamoylenkVi commented on src/components/film-card.jsx
> +        {isVideoError && <img src={previewImage} alt={altText} width="280" height="175" />}
fixed

2023-05-19 06:04 UTC, SamoylenkVi commented on src/components/film-details-review/filmDetailsReview.jsx
> +  comments: PropTypes.objectOf(),
fixed

2023-05-19 06:08 UTC, Pavel-Liteiniy commented
Approved, good job! 👍

2023-05-19 06:19 UTC, merged